export type LocalPreviewAsset = { id: string; kind: "local_2d_preview"; origin: "fixed_local_template"; generatedByAi: false; mimeType: "image/svg+xml"; width: 1080; height: 1920; aspectRatio: "9:16"; beat: string; captionDraft: string; dataUri: string; };
export type StudioProject = { id: string; status: "local_preflight_ready" | "review_required" | "queued" | "in_progress" | "completed"; sourceRelationship: "original" | "inspired" | "licensed"; localPrecheck: { status: "not_a_policy_decision"; outcome: string; blockedRules: string[]; notice: string }; referenceMedia: null | { name: string; mimeType: string; purpose: string; transfer: "metadata_only"; screening: "not_performed" }; storyboard: { format: string; seconds: number; captions: string; beats: Array<{ start: string; end: string; label: string; direction: string }> }; job: null | { id: string; provider: "local-template"; mode: "local_2d_preview"; status: string; progress: number }; delivery: null | { mode: "local_2d_preview"; notice: string; assets: LocalPreviewAsset[] }; };
export type ProjectDraft = { scene: string; sourceRelationship: "original" | "inspired" | "licensed"; rightsAccepted: boolean; direction: string; referenceMedia?: { name: string; mimeType: string; purpose: "setting" | "lighting" | "composition" | "movement" }; };
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } }); const body = await response.json() as T & { error?: string; message?: string; errors?: Array<{ message: string }> }; if (!response.ok) throw new Error(body.message ?? body.error ?? body.errors?.[0]?.message ?? "Studio API request failed."); return body; }
export const fetchStudioHealth = () => request<{ status: "ok"; provider: "local-template"; mode: "local_2d_preview"; message: string }>("/api/health");
export const createStudioProject = async (draft: ProjectDraft) => (await request<{ project: StudioProject }>("/api/projects", { method: "POST", body: JSON.stringify(draft) })).project;
export const approveStudioProject = async (projectId: string) => (await request<{ project: StudioProject }>("/api/projects/" + projectId + "/approve", { method: "POST" })).project;
export const fetchStudioProject = async (projectId: string) => (await request<{ project: StudioProject }>("/api/projects/" + projectId)).project;
export type PhotoMode = "text_to_photo" | "animation_2d_to_photo";
export type PhotoOutputKind = "still" | "motion_gif";
export type PhotoConditions = { subject: "no_person" | "fictional_adult"; age: "not_applicable" | "adult_20s" | "adult_30s" | "adult_40s" | "adult_50_plus"; era: "contemporary" | "nineties" | "historical" | "future"; setting: "city_night" | "sunlit_room" | "coastal_nature" | "studio_set"; presentation: "unspecified" | "feminine" | "masculine" | "androgynous"; framing: "portrait" | "upper_body" | "full_body" | "hands_detail"; cameraAngle: "eye_level" | "low_angle" | "high_angle" | "three_quarter"; clothing: "casual" | "tailored" | "historical" | "functional"; peopleCount: "zero" | "one" | "two" | "group"; };
export type PhotorealisticCleanupWarning = { code: string; osCode?: string; workspace?: string; };
export type PhotorealisticProviderDiagnostics = { diagnosticCode: string; exitCode?: number; signal?: string; elapsedSeconds?: number; stderrBytes?: number; stderrTruncated?: boolean; timeoutSeconds?: number; };
export type PhotorealisticAsset = { id: string; kind: "user_photorealistic_still" | "user_motion_gif"; origin: "codex_headless_imagegen" | "local_motion_gif_from_generated_still"; generatedByAi: true; mimeType: "image/png" | "image/gif"; width: number; height: number; aspectRatio: "9:16"; frameCount: number; fps: number | null; durationSeconds: number | null; byteLength: number; dataUri: string; notice: string; cleanupWarning?: PhotorealisticCleanupWarning; };
export type PhotorealisticProject = { id: string; status: "queued" | "in_progress" | "completed" | "failed"; mode: PhotoMode; conditions: PhotoConditions; detailPrompt: string; composedPrompt: string; output: { kind: PhotoOutputKind; frameCount: number; fps: number | null }; source: null | { kind: "attested_original_2d"; processing: "ephemeral_codex_image_attachment" }; job: { id: string; provider: string; mode: PhotoMode; outputKind: PhotoOutputKind; requestedFrameCount: number; encodedFrameCount: number; fps: number | null; status: string; phase: "validated" | "workspace_prepared" | "provider_started" | "output_validated" | "gif_encoding" | "artifact_ready" | "completed" | "failed"; progress: number | null; observedProgress: number | null; forecastHighWater: number; progressBasis: "observed_server_lifecycle" | "server_lifecycle_and_duration_forecast"; startedAt: string | null; phaseStartedAt: string | null; forecastStartedAt: string | null; completedAt: string | null; estimatedDurationSeconds: number; elapsedSeconds: number; forecastElapsedSeconds: number; estimatedRemainingSeconds: number | null; etaState: "bootstrap" | "sampled" | "estimate_exceeded" | "terminal"; etaSource: "bucket_bootstrap" | "bucket_median" | null; durationSampleCount: number; }; delivery: null | { mode: PhotoMode; output: { kind: PhotoOutputKind; frameCount: number; fps: number | null }; notice: string; asset: PhotorealisticAsset }; error: null | { code: string; message: string; providerDiagnostics?: PhotorealisticProviderDiagnostics; cleanupWarning?: PhotorealisticCleanupWarning }; };
export type PhotorealisticProjectDraft = { mode: PhotoMode; outputKind: PhotoOutputKind; frameCount: number; detailPrompt: string; conditions: PhotoConditions; rightsAccepted: boolean; clientRequestId: string; referenceImage?: { mimeType: "image/png" | "image/jpeg" | "image/webp"; dataUrl: string }; };
export const createPhotorealisticProject = async (draft: PhotorealisticProjectDraft) => (await request<{ project: PhotorealisticProject }>("/api/photorealistic-projects", { method: "POST", body: JSON.stringify(draft) })).project;
export const fetchPhotorealisticProject = async (projectId: string) => (await request<{ project: PhotorealisticProject }>("/api/photorealistic-projects/" + projectId)).project;