import { createServer } from "node:http";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { SNAPSHOT_SCHEMA_VERSION, appendAgentEvent, collectDashboardSnapshot, defaultEventPath } from "./dashboard-observability.mjs";

const reply = (response, status, value) => { response.writeHead(status, { "Cache-Control": "no-store", "Content-Type": "application/json; charset=utf-8" }); response.end(JSON.stringify(value)); };
const body = async (request) => { const chunks = []; let bytes = 0; for await (const chunk of request) { bytes += chunk.length; if (bytes > 32_768) throw new Error("Request body exceeds 32 KiB."); chunks.push(chunk); } return Buffer.concat(chunks).toString("utf8"); };
export const createDashboardServer = (options = {}) => { const root = path.resolve(options.root ?? process.cwd()); const eventPath = options.eventPath ?? defaultEventPath(root); const snapshotOptions = options.snapshotOptions ?? {}; const collectorTtlMs = options.collectorTtlMs ?? 30_000; let cachedCollectors = snapshotOptions.collectors ?? null, cachedRepository = snapshotOptions.repository ?? null, collectorsCachedAt = cachedCollectors && cachedRepository ? Date.now() : 0; const snapshot = () => { const reuseStatic = cachedCollectors !== null && cachedRepository !== null && Date.now() - collectorsCachedAt < collectorTtlMs; const value = collectDashboardSnapshot({ ...snapshotOptions, ...(reuseStatic ? { collectors: cachedCollectors, repository: cachedRepository } : {}), root, eventPath, heartbeatTtlMs: options.heartbeatTtlMs }); if (!reuseStatic) { cachedCollectors = value.collectors; cachedRepository = value.metrics.repository; collectorsCachedAt = Date.now(); } return value; }; if (options.prewarm) snapshot(); return createServer(async (request, response) => { const url = new URL(request.url ?? "/", "http://127.0.0.1"); if (request.method === "GET" && url.pathname === "/api/health") return reply(response, 200, { ok: true, schemaVersion: SNAPSHOT_SCHEMA_VERSION, generatedAt: new Date().toISOString() }); if (request.method === "GET" && url.pathname === "/api/observability/snapshot") return reply(response, 200, snapshot()); if (request.method === "GET" && url.pathname === "/api/observability/events") { response.writeHead(200, { "Cache-Control": "no-cache, no-transform", Connection: "keep-alive", "Content-Type": "text/event-stream; charset=utf-8" }); const send = () => response.write("event: snapshot\ndata: " + JSON.stringify(snapshot()) + "\n\n"); send(); const timer = setInterval(send, 2_000); request.on("close", () => clearInterval(timer)); return; } if (request.method === "POST" && url.pathname === "/api/observability/events") { try { return reply(response, 201, { event: appendAgentEvent(JSON.parse(await body(request)), { eventPath }) }); } catch (error) { return reply(response, 400, { error: error.message }); } } if (request.method !== "GET" && request.method !== "HEAD") return reply(response, 405, { error: "Method not allowed." }); if (url.pathname !== "/" && url.pathname !== "/dashboard/index.html") return reply(response, 404, { error: "Not found." }); const dashboard = path.join(root, "dashboard", "index.html"); if (!existsSync(dashboard)) return reply(response, 404, { error: "Dashboard file is missing." }); response.writeHead(200, { "Cache-Control": "no-store", "Content-Type": "text/html; charset=utf-8" }); return request.method === "HEAD" ? response.end() : response.end(readFileSync(dashboard)); }); };
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) { const port = Number(process.env.DASHBOARD_PORT ?? 4173); createDashboardServer({ prewarm: true }).listen(port, "127.0.0.1", () => process.stdout.write("AI Project control plane: http://127.0.0.1:" + port + "/\n")); }
