import assert from "node:assert/strict";
import test from "node:test";
import { StudioService } from "./studio-service.mjs";

const validRequest = { scene: "A commuter pauses at a rain-soaked station, then gives a hand-written apology to a friend before the final train departs.", sourceRelationship: "original", rightsAccepted: true, direction: "rainy-station" };
test("creates a local preflight record with a fixed 15-second vertical storyboard", () => { const result = new StudioService().createProject(validRequest); assert.equal(result.status, 201); assert.equal(result.project.status, "local_preflight_ready"); assert.equal(result.project.localPrecheck.status, "not_a_policy_decision"); assert.equal(result.project.storyboard.seconds, 15); assert.equal(result.project.storyboard.format, "1080x1920"); });
test("does not queue inspired material without rights review", () => { const service = new StudioService(); const created = service.createProject({ ...validRequest, sourceRelationship: "inspired" }); assert.equal(created.project.status, "review_required"); assert.equal(service.approveStoryboard(created.project.id).status, 409); });
test("blocks obvious protected-work, copied-scene, and real-person requests in local precheck", () => { const service = new StudioService(); for (const scene of ["원피스 루피가 등장하는 장면을 정확하게 재현해 줘. 카메라는 원작과 똑같이 움직인다.", "유명인 얼굴과 목소리로 실제 인터뷰 장면을 만들어 줘. 현실의 인물을 그대로 재현한다."]) { const result = service.createProject({ ...validRequest, scene }); assert.equal(result.status, 422); assert.equal(result.errors[0].field, "scene"); } });
test("stores reference input only as unverified metadata", () => { const result = new StudioService().createProject({ ...validRequest, referenceMedia: { name: "street-light.jpg", mimeType: "image/jpeg", purpose: "lighting" } }); assert.equal(result.status, 201); assert.equal(result.project.referenceMedia.transfer, "metadata_only"); assert.equal(result.project.referenceMedia.screening, "not_performed"); });
test("moves a local-preflight project through the entire mock lifecycle deterministically", () => { const scheduled = []; const service = new StudioService({ schedule: (work) => scheduled.push(work) }); const created = service.createProject(validRequest); assert.equal(service.approveStoryboard(created.project.id).status, 202); assert.equal(service.getProject(created.project.id).project.status, "queued"); scheduled.shift()(); assert.equal(service.getProject(created.project.id).project.status, "in_progress"); scheduled.shift()(); const project = service.getProject(created.project.id).project; assert.equal(project.status, "completed"); assert.equal(project.delivery.mode, "simulation"); assert.deepEqual(project.delivery.assets, []); });